// <auto-generated />
namespace HotelCW.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addedcommentsagain : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedcommentsagain));
        
        string IMigrationMetadata.Id
        {
            get { return "202105221823126_added comments(again)"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
